
SMS_CODE_HEADER_NAME = 'Sms-Code'
TOKEN_TIMEOUT_NAME = 'TOKEN_TIMEOUT'
SALT_KEY_NAME = 'salt_key'
BEARER_STRING_NAME = 'Bearer '
TOKEN_CONFIRM_TIMEOUT_NAME = 'TOKEN_CONFIRM_TIMEOUT'
PASS_SALT_NAME = 'SECURITY_PASSWORD_SALT'
